### ISSUE TITLE
Manage Items in Groups

### ISSUE THREAD

**Issue by sam-berg** [Esri/ago-assistant#124]
Hi, we have a use case that I propose might be a nice ago-assistant fit: the ability to Manage items in groups that you belong to.  The main use case is to copy/register items (that you don't necesssarily own) from one portal group to another.  So the option to search for a view items in groups and then copy to (register the existing underlying URLs) another portal would be helpful.  Thanks.

**Comment by ecaldwell** [comment]
OK, I'm thinking two components to this.

1. Add an option to "View My Groups" that would list out all items shared with groups that you are a member of (organized by group instead of folders).
![screen shot 2016-03-24 at 4 27 06 pm](https://cloud.githubusercontent.com/assets/240542/14030381/b987e1da-f1dd-11e5-8afc-4ff42edd7630.png)

2. Copy Groups. It would probably be useful to wholesale copy a group you had setup and all of its items.

**Comment by nheminger** [comment]
Great idea to split it up into View my Groups and the copy!

So for the "View My Groups", would that functionality find all groups you are a member of and then for each of those groups list all items in that groups regardless if you own it or not? Then once you have the folders for the group, would you be "copying" the whole folder or individual items within that group?

Just brainstorming on how this would work... Is this the same as a copy (existing functionality) followed by a an "update sharing properties" operation (potential new functionality), to make it first copied to the target portal and then subsequently shared out with the new target group?

I'm trying to understand how this would work, as I believe each item has a specific owner and that ownership is treated separately from the group it is shared with. Does that sound correct? So would a "copy from one portal group to another portal's target group" actually be a "copy from one portal's specific user to a different portal's different user" followed by a "share" to a designated group in the targeted portal?

Breaking this down into how the copying, ownership, and sharing works I think is helpful to handle the workflow.

**Comment by ecaldwell** [comment]
> So for the "View My Groups", would that functionality find all groups you are a member of and then for each of those groups list all items in that groups regardless if you own it or not?

Yes, that's pretty much exactly how I was picturing it. Copying would be on the item itself, just like copying an item you found with a search across ArcGIS Online.

I don't think any sharing needs to be updated with component 1 (copying group content). In component 2 (copying a group) I think there should be some options presented to the user...maybe as checkboxes. The main copy of the group should just grab all the normal details you specify when creating a new group (title, thumbnail, etc). Then checkboxes for:
* items (shared with the new group by default)
* members (ArcGIS Online members can be added across organizations)
* any others?

I took a shot at part 1. It's on [a new branch on my fork](https://github.com/ecaldwell/ago-assistant/tree/feature_Groups). I also [hosted it on a staging server](https://s3.amazonaws.com/ago-assistant-staging/index.html) so you can easily play with it. Give it a shot @nheminger and @sam-berg and let me know what we need to change.

**Comment by nheminger** [comment]
@ecaldwell Wow, that was fast! Awesome, looks good! :smiley:

I'm having trouble pinning this down in my head still :confused:. So are component 1 and component 2 going to be distinct tools? So component 1 finds all the items in the groups and names the folders after the groups... But then when it comes for component 2 to "copy" the group, is it going to be a drag and drop of each single item in those folders one by one?

For component 2 a couple of questions:
1. When copying the items should those be owned by the account used to login to the target? Or owned by members that are copied over?
2. For the copying of members, are you saying that those members should get an invite/add to the group in the target location? Or should it create new accounts at the target location? If creating new accounts, what should the passwords be?

**Comment by ecaldwell** [comment]
I see components 1 & 2 as two distinct operations, but not sure how to best distinguish them in the UI. One option is to add an "item" at the top of the list in each group that represents the group itself. Dragging that would copy the group and prompt the user to specify what else should be copied (all items and members).

>1. When copying the items should those be owned by the account used to login to the target? Or owned by members that are copied over?

Owned by the destination account. Otherwise this tool would only be useful to admins (who could copy into a different user's account).

>2. For the copying of members, are you saying that those members should get an invite/add to the group in the target location? Or should it create new accounts at the target location? If creating new accounts, what should the passwords be?

Invites are an option, but we could also just force add them. This is only viable for ArcGIS Online orgs.

>3. If copying members, should each members content also get copied over somehow? Even if it isn't shared with the group?

No, I think it should just copy membership. Again, this only works in the context of ArcGIS Online where users can span orgs.

There would probably be value in a third component to this: cloning a group. In that case, you'd be copying the group, members, copying member items, rehooking things up on the destination, etc. That's a much larger effort that would probably be best to separate from this.

**Comment by ecaldwell** [comment]
Closing this out since the original criteria has been met with #126. Copying groups should be open as a separate issue/enhancement.
