### ISSUE TITLE
change url of map service in web map

### ISSUE THREAD

**Issue by ClaireBrill** [Esri/ago-assistant#128]
I used the ago-assistant to change the URL for the map service in a web map.  I am replacing the current map service with a secured map service.  When I look at the item details for the web map in My Content for my ArcGIS Online organization, the URL is for the correct secured service. However, when I select item details for the layer in the web map, it takes me to the unsecured map service.  How can I be sure the change URL process worked and no one will be using the unsecured service?

**Comment by ecaldwell** [comment]
It's likely that the item details are launching based on the `itemId` property of that layer. Take a look at the JSON of the layer and see if the `itemId` references the old layer. You can update it there to reflect the new URL's `itemId`. You may also be able to remove it, but I'm not sure what will happen when you click the "item details" from the layer's context menu in the web map.

**Comment by ecaldwell** [comment]
Were you able to test this?

**Comment by ClaireBrill** [comment]
No, I had to move on to another project so I haven't tested.

**Comment by eapalins** [comment]
Thanks for including me here.  I tested the JSON fix by updating the itemId in the maps JSON and it now points to the new itemId and description.  One problem with this fix.  The service must be registered with AGO in order to have an itemId.  You cannot bring the layer directly into a webmap from ArcGIS Server.  You must first register the layer in your AGO org then use the itemId from that layer.  This fixes the issue with the details pointing to the incorrect url, however it adds to the number of layers I need to manage in my organization.
Thanks for the help!

**Comment by slibby** [comment]
@eapalins for a layer added to a webmap directly from ArcGIS Server (not from an Item), the original method of editing the JSON to change the URL should be sufficient. Are you seeing that not work?

**Comment by eapalins** [comment]
@slibby Editing the JSON does work, what was happening was if I brought a service from ArcServer into the map directly, updated the service url, the item page did not update because, there technically was not an item page for the service.  To fix this I register the service in our Org, share with everyone, bring this item into the map.  I can then change the JSON for this item.  Thanks

**Comment by rwmajor2** [comment]
@ClaireBrill @eapalins Do we feel this issue has been discussed and understood?  Just looking to close it out to clean up some issues.

**Comment by eapalins** [comment]
@rwmajor2  I am able to update the URL and JSON using the ago assistant so from my end yes I think it is resolved.
