### ISSUE TITLE
login button is disabled

### ISSUE THREAD

**Issue by wzhu1** [Esri/ago-assistant#174]
I downloaded the recent release ago-assistant-2.7.2.zip from https://github.com/Esri/ago-assistant/releases and installed the ago-assistant tool on my local server. But the login button is disabled. The language setting for my browser is English(United States). Anyone have any idea about this? 
thanks!

**Comment by jgravois** [comment]
> But the login button is disabled

which login button? `Log in to ArcGIS Online`? 
do you mean that its grayed out and not clickable, or that clicking it generates an error?

**Comment by jgravois** [comment]
looks like something similar was logged in #101.  what happens when you set the browser locale to English (US)?

**Comment by wzhu1** [comment]
Yes. The button is grayed out and not clickable.

**Comment by wzhu1** [comment]
Thanks. My browser locale is English(US).

**Comment by jgravois** [comment]
i can't reproduce that behavior on my side. if you could open up the browser [developer tools](https://developer.chrome.com/devtools) and let us know whether an error is being logged or a resource is failing to load, that would be _really_ helpful.

**Comment by wzhu1** [comment]
Here is error from Console I sent to Bill Major before:

Uncaught TypeError: b.Portal is not a constructor
    at main.min.js:2
    at qa (dojo.js:16)
    at dojo.js:16
    at pa (dojo.js:16)
    at la (dojo.js:16)
    at d (dojo.js:18)
    at HTMLScriptElement.<anonymous> (dojo.js:21)
(anonymous) @ main.min.js:2
qa @ dojo.js:16
(anonymous) @ dojo.js:16
pa @ dojo.js:16
la @ dojo.js:16
d @ dojo.js:18
(anonymous) @ dojo.js:21

**Comment by wzhu1** [comment]
Hi,

I installed agoassistant on another machine and have the same problem.

Thanks,
Weihong

[cid:image002.png@01D2B2A6.2146F7A0]
From: Weihong Zhu
Sent: Monday, April 10, 2017 3:41 PM
To: 'Esri/ago-assistant' <reply@reply.github.com>; Esri/ago-assistant <ago-assistant@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Esri/ago-assistant] login button is disabled (#174)


Here is error from Console I sent to Bill Major before:

Uncaught TypeError: b.Portal is not a constructor
    at main.min.js:2
    at qa (dojo.js:16)
    at dojo.js:16
    at pa (dojo.js:16)
    at la (dojo.js:16)
    at d (dojo.js:18)
    at HTMLScriptElement.<anonymous> (dojo.js:21)
(anonymous) @ main.min.js:2
qa @ dojo.js:16
(anonymous) @ dojo.js:16
pa @ dojo.js:16
la @ dojo.js:16
d @ dojo.js:18
(anonymous) @ dojo.js:21

**Comment by ecaldwell** [comment]
Is this happening in multiple browsers (Chrome, Firefox, etc)?

**Comment by wzhu1** [comment]
This happened on Chrome, Firefox and IE.

Thanks,
Weihong

**Comment by ecaldwell** [comment]
Have you tried downloading again just to rule out any issues with the original zip file? Also, just double checking, can you confirm you downloaded the built app and not the source code?
https://github.com/Esri/ago-assistant/releases/download/v2.7.2/ago-assistant-2.7.2.zip

**Comment by wzhu1** [comment]
Thanks for your help. I downloaded zip ago-assistant-2.7.2.zip<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Esri_ago-2Dassistant_releases_download_v2.7.2_ago-2Dassistant-2D2.7.2.zip&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=IGWHdPjiPiCoVLuGExJXbMstDS1u4bWEBIym1m9b-aMksT-KuCdOawz3Nst6CbUmS9GArHmDyxskn0FnmKxPRHe7XSdo4IrHr8H8JV19VElFRF0UyUk1LNicWXheQwf16-7c9zcuhDijEh08wnEGCA&m=d0ZqrEd6QN3PrrIWaTs3TCOFSePa3iW_aFEXFs-KbyI&s=dE_WQ9kL9jHj9xy1LF6MPhuVEs8uEk0uwnoNSI6PV0w&e= > from https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Esri_ago-2Dassistant_releases&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=IGWHdPjiPiCoVLuGExJXbMstDS1u4bWEBIym1m9b-aMksT-KuCdOawz3Nst6CbUmS9GArHmDyxskn0FnmKxPRHe7XSdo4IrHr8H8JV19VElFRF0UyUk1LNicWXheQwf16-7c9zcuhDijEh08wnEGCA&m=d0ZqrEd6QN3PrrIWaTs3TCOFSePa3iW_aFEXFs-KbyI&s=IYWi8uzR1sPKxocHBIVMKQxPlsjMhljlBozOZlPzIdc&e=  and followed the steps in readme file to generate the build folder, and then copy the files under builder folder to IIS Server.

Thanks,
Weihong

**Comment by ecaldwell** [comment]
OK, two issues. I think you've got a mismatch of folders because you shouldn't be able to "build" the app from the zip file I linked. That's the pre-built app with no dev components. I just downloaded and verified it works fine. Here are two things to try troubleshooting next.

First, try downloading the [latest release](https://github.com/Esri/ago-assistant/releases/download/v2.7.2/ago-assistant-2.7.2.zip) and unzip to a clean directory. That is the pre-built app so you don't need to do anything other than copy it to IIS and load it.

Second, if you want to build the app from the source, then double check that you have installed all of the dependencies with `npm install` and that there aren't any errors during that or the build step. If your error messages above are from a custom build, then it looks like there is a problem with the portal library which would indicate a problem with the rollup step in grunt.

Give those a shot and let us know what happens.

**Comment by wzhu1** [comment]
Thanks Evan. The “Log in to ArcGIS Online” button is working now. But after clicked it, I got this error:

[cid:image003.jpg@01D2B2B1.84F09300]


When I tried to build the app from the source, I didn’t get any error but get warning message. Do I have to build the app if I want to modify the app?

Thanks,
Weihong

**Comment by ecaldwell** [comment]
The screenshot isn't coming through, but I'm guessing it says "invalid redirect_uri." To use your own app id (or to further customize the app) you'll need to build it from source. The [instructions](https://github.com/Esri/ago-assistant#using-grunt) step you through that process, but it sounds like you've already started down that path. What are the warnings you get during the build?

**Comment by wzhu1** [comment]
Here is the warning I got during the build:

[cid:image002.png@01D2B2B4.62FA8B90]

This error when I used the pre-build:
[cid:image003.png@01D2B2B4.62FA8B90]


In order to make the app work, I have to build from the source. I can’t just use the pre-build you gave me?

Thanks,
Weihong

**Comment by ecaldwell** [comment]
The screenshots aren't coming through. Can you paste the text?

The reason it's not working out of the box is because it is registered for OAuth in an ArcGIS Online org with a pre-defined set of valid redirect URIs and your local dev server is not registered as one of those URIs. When you register the app in your own org, you can add a redirect URI for your own dev environment so it will work.

Portal logins should work out of the box (OAuth is only used for ArcGIS Online logins in this app). A workaround to your immediate issue is to bypass OAuth: select the Portal option, then enter `https://www.arcgis.com` as your portal url and then your normal org credentials. That will bypass OAuth and get you into your account.

**Comment by wzhu1** [comment]
Here is all the message when I run grunt:

C:\projects\JSprojects\content_agoassistant>grunt
Running "clean:src" (clean) task
>> 0 paths cleaned.

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "string-replace:config" (string-replace) task

1 files created

Running "string-replace:version" (string-replace) task

2 files created

Running "eslint:all" (eslint) task

Running "shell:command" (shell) task
'rollup' is not recognized as an internal or external command,
operable program or batch file.
Warning: Command failed: rollup -c
'rollup' is not recognized as an internal or external command,
operable program or batch file.
Use --force to continue.

Aborted due to warnings.


Thanks,
Weihong

**Comment by jgravois** [comment]
@wzhu1 if you want to upload screenshots, drag and drop them when posting your message directly on https://github.com/Esri/ago-assistant/issues/174

you can't just reply to your email notification and include an attachment.

**Comment by ecaldwell** [comment]
Rollup isn't installed. Try installing it globally from the command line `npm install -g rollup@0.34.10`, then run the build again.

**Comment by wzhu1** [comment]
Thanks Evan. The build is working now and the app is working on my local server.

Weihong

**Comment by ecaldwell** [comment]
Great! I'll take a look and see if we can clarify how to deploy the app in the documentation.

**Comment by wzhu1** [comment]
Your help is greatly appreciated.

Weihong
