### ISSUE TITLE
Saving Webmap json

### ISSUE THREAD

**Issue by steveoh** [Esri/ago-assistant#190]
I'm fooling with adding bookmarks to a web map programmatically and I thought I would use this app to see what endpoints were available. While testing I noticed a few things that I thought you might want to be aware of.

### Url formatting

First, I think [these lines](https://github.com/Esri/ago-assistant/blob/master/src/js/main.js#L420-L423) and [this one](https://github.com/Esri/ago-assistant/blame/0cf32dbfa58e1263a79c038857bd14562a79c9f3/src/js/portal/content/updateData.js#L8) are creating urls like `https://arcgis.com/sharing/rest/content/users/{user}///items/{id}/update` with extra `/`'s when there isn't a folder. 

### Network traffic
Upon clicking save, the same payload was posted 3 times to the server which seems a bit inefficient. 

I don't have a local repo to debug with but I'd be happy to help figure this out with you all since this is a great time saving project!

**Comment by ecaldwell** [comment]
You're absolutely right; the formatting of urls needs some cleanup especially when it's the root folder. We can use an empty string instead of `/` for the root folder, but that would still leave two forward slashes in your example. Do you have any thoughts on an alternative approach?

I've seen similar behavior with multiple posts. If you start from scratch (refresh the app) and go directly through that workflow once, does it still post multiple times? I suspect this is caused by old listeners not getting cleaned up when switching context in the "I want to" menu.

**Comment by steveoh** [comment]
I'd have to look at how the urls are created a bit closer but I came into the app and updated a webmap json and it posted 3 times. That was on a fresh load with no event leaks I'm pretty sure. 

I'd be happy to talk about it in the slack chat next week.

**Comment by jgravois** [comment]
quit breaking the platform @steveoh and lets see a PR! 👯‍♂️

**Comment by steveoh** [comment]
Ok @jgravois 

![challenge accepted](http://media.giphy.com/media/iHae1GDslayOs/giphy.gif)
