### ISSUE TITLE
Enhancement: grep-like ability to change multiple URLs in a web map.

### ISSUE THREAD

**Issue by JeffJacobson** [Esri/ago-assistant#37]
It would be useful to have a [grep]-like ability to change the URL references in a web map.

For example, say I have a bunch of services on `beta.example.com` and want to move them to `www.example.com`. Currently it is possible, but I would need to change these URLs one by one. :turtle: It would be nice to have a faster way to do this. :rabbit2: 

[grep]:https://en.wikipedia.org/wiki/Grep

**Comment by GISDev01** [comment]
@JeffJacobson @ecaldwell This is a pretty old ticket, but I would like to contribute to this repo and I think I can tackle this one pretty quickly over the long weekend. I have needed this many times, and always just copy-paste the JSON into Sublime for a Global Find/Replace on the URL's, but having this in the UI would be great. 

(I will implement it for a single webmap for now, and then we could always extend it for every item in a user's account or even every URL within an Org. if that was ever needed)

**Comment by ecaldwell** [comment]
Sounds great! I was just talking through this with @rwmajor2. One issue is figuring out how the UI might change to support it. What about an "administrative" view for doing these types of bulk tasks?

**Comment by GISDev01** [comment]
For just the functionality part, I am taking a look now, and I was thinking we could just add a new button on the same row as the 2 existing buttons (Reset and Update), but pull the new button to the left side on the pane. Possibly name the button "Bulk URL Edit"? Clicking the button will open a simple modal that is basically just "Old Root URL" and "New Root URL" or something like that? Maybe the "Old Root URL" input could be a pre-populated dropdown list by reading all the existing Root URLs within the webmap layers.

It does seem like adding buttons all over will over-complicate the UI very quickly (I'm no UI/UX expert, that's for sure), so I'm happy to move this functionality anywhere else you guys deem appropriate.

**Comment by ecaldwell** [comment]
I like the idea of a dropdown for the old url. I agree that the buttons may start to get unwieldy. What about a button up at the top to toggle between simple and batch modes. Then you can just add a new template for the batch mode.

I've often thought about what this app would look like (both UI and code) if I were to start writing it from scratch today. One of the things that I often picture is more like a set of possible options for a given item. Rather than filtering them on the left, they're all just there and then the type of each item dictates what can be done with it on the right. Selecting more than one item might then expose some bulk oriented tasks. I imagine this app would be much easier to extend if it was using a proper framework like react or ember.

**Comment by yeonkim** [comment]
I have to batch update many map service URLs used in web maps, and am very happy to find this functionality. Thank you so much for implementing this!!

Yeon

**Comment by GISDev01** [comment]
@yeonkim, Happy to hear that it is still helping out others!
