### ISSUE TITLE
Update map service URL's not working

### ISSUE THREAD

**Issue by jschuckert** [Esri/ago-assistant#65]
I am using the AGO Assistant tool (signing in directly from: https://ago-assistant.esri.com/ ) to try and re-source several map service URL's however the tool is very finicky. Sometimes it will successfully update the URL's after clicking "Update", however most of the time after checking the web map in ArcGIS Online I realize the tool is not actually saving the new URL path. I put in new path, hit update, but the old path seems to persist even after several attempts. In the past I have used the tool to re-source just one map service URL here and there--those times everything worked just fine. Is there something I should be doing differently or is the tool really this unreliable? Thanks.

**Comment by ecaldwell** [comment]
It *should* be working consistently (or at least warning you when it can't update the web map), but that's not to say there aren't bugs here and there. I just pushed a big update in the past few days and it's possible that some new bugs were introduced.

I haven't seen any issues with updating services in a web map. Can you detail the behavior you're seeing? Is it giving you a success message? Are you updating web maps in ArcGIS Online or in a Portal? Do you own the web maps or are they owned by someone else?

**Comment by jschuckert** [comment]
Certainly, and thanks for such a quick reply. I am signed into the AGO Assistant tool as an administrator, I created and own the web map using that sign in, and the map services are being published to our local server. I am having spotty results trying to update the map service ULR's of several layers within one web map, sometimes it works but quite a few times it doesn't. When I attempt to update the URL's I do receive the green box message reading "Success!" on the AGO Assistant page. After I hit "Update" and receive the "Success" message, it appears that the URL has been updated since I can see the new URL link right on that page. However, when I go back into ArcGIS Online and look at the web map details the old link still persists. My ultimate goal in using the tool is to consolidate map services where possible as opposed to one layer in one mxd published to produce one map service. I have been testing the tool with map services containing just a single layer and map services containing several layers, in both cases I am getting inconsistent results. One thing to note, after a failed attempt to updated a service I seemed to have more success when completely signing out of the AGO Assistant then signing back in and retrying. It almost seems like I can't make several changes in one sesssion. Of course repeatedly signing in/out isn't very productive. Any ideas or suggestions?

**Comment by ecaldwell** [comment]
I wasn't able to replicate the issue you were seeing (all of my updates were taking effect), but I did find another bug in the same area that could be related. I've fixed that and am curious if your issue is also now resolved. Let me know.

**Comment by jschuckert** [comment]
I was able to narrow down what the issue is, here is what I am finding. The tool works well and consistently only when I use the update function just one time for that particular web map. If I decide after the fact that I want to update a second service within that same web map or re-source that same layer again (the one I had previously updated), then I have to either log out/in of the site OR navigate away from that particular page then navigate back and re-do the update process. In all of my testing I am consistently getting the green message box the reads "Success!", I just noticed I need to perform these extra steps for the tool to truly re-source my layers. Not a huge deal, although more time consuming. That being said, there is a good chance the tool was not designed to update more than once so maybe that is why I am running into this issue. In most cases I wouldn't re-source something several times, however I was doing some testing and that is the main reason why. Thanks again for your responses and help. For now, I will just know this particular limitation unless something changes. All being said, a great and very useful tool!

**Comment by ecaldwell** [comment]
Thank you for providing so much detail. I see the issue now. 

I was storing the original URL for each service in an attribute called `data-original` to replace any edits if the reset button was clicked. After a successful update, this attribute was not being updated to reflect the newly changed value. Navigating away and back in would refresh the `data-original` tag to reflect the current value which is why it always worked right the first time, but not on successive updates from the same dialog.

Thanks again for helping me squash this one! :beers:

**Comment by jschuckert** [comment]
Absolutely, no problem at all. I am glad we can collaborate to make the such enhancements, this is great.

Thanks again for all your responses and help!

**Comment by TViveiros** [comment]
Hello...I experienced this issue recently with URL changes not persisting in AGOL Assistant.  Although the 'Success' message appeared after I changed the path from http to https, when I revisited the service URLs some days later (today), the URLs for the services in the web map were still http. I've since changed them to https again and the changes seem to be persisting; however, this has created an issue with disconnected data collected using Collector for ArcGIS not properly syncing now (url address incorrect because our organization enabled https). I've done some additional AGOL Assistant testing and have discovered that I cannot successfully change the URL path of one layer service (the data) from https to http (not something I really want to do).  Although 'Success' appears, upon refreshing the browser or exiting AGOL Assistant and returning, https still exists, i.e. the https to http change is not persisting.
