### ISSUE TITLE
portal 10.2.1 content can't been shown

### ISSUE THREAD

**Issue by gischen** [Esri/ago-assistant#87]
When I used this tool to migrate portal 10.2.1 content to portal 10.3. I find a problem when I log in portal 10.2.1, but in the left panel, can’t list content of portal 10.2.1, just like image below.
![dddd](https://cloud.githubusercontent.com/assets/3838380/7783251/e427763c-016d-11e5-8637-d50c63f137a6.jpg)

Then I check the portal 10.2.1 rest API version, I find it is 2.3.
At the same, I log in portal 10.3, The content from portal 10.3 can be listed. I check the portal 10.3 rest API version, I find it is 3.5.
I don’t know if you had encountered this issue.
 
I want to know this tools need which version of portal rest API. Or how to modify code. 
Waiting for your reply, Thanks a lot!

**Comment by ecaldwell** [comment]
You shouldn't have any problems with Portal 10.2.1. When I have seen this kind of issue before, it has been caused by a corrupted item (malformed JSON) in your content. Here are a few troubleshooting steps to try.
  1. Once you have signed in, try searching for content (your own, or just an open ArcGIS Online search) and see if you get results back.
  2. Try signing in with a different account and see if content shows up for that account.
  3. Make sure this account actually has content to display. :-)

**Comment by ecaldwell** [comment]
Did you have a chance to try any of the troubleshooting steps?

**Comment by gischen** [comment]
Hi evan,
sorry to delay reply, we encounter this issue when we plan to upgrade portal from 10.2.1 to 10.3. Finnaly  we directly install portal 10.3 on 10.2.1 machine. so we have no chance to verify what you advice.
Best.

**Comment by ecaldwell** [comment]
No worries!
