### ISSUE TITLE
KML Data Error... Viewing JSON

### ISSUE THREAD

**Issue by kevinsigwart** [Esri/ago-assistant#88]
If you have a KML registered in Portal 10.3 and you want to view the JSON.  You get an error for Data.  See screenshot below.

![capture](https://cloud.githubusercontent.com/assets/3045382/8037427/a4864aa2-0dcb-11e5-9863-a4cb55679d28.PNG)

**Comment by ecaldwell** [comment]
OK, I'm seeing the same thing for registered KMLs (i.e. hosted somewhere else). I'm not sure why the data response comes back with an error. When you do the same thing with registered Map Services, the `/data` response comes back empty.

Would you expect to see anything in the data display (like the parsed KML) or just nothing (like the Map Service behavior)?

**Comment by kevinsigwart** [comment]
I'm seeing this with a KML Service.  Does a KML file and a KML service show up the same in Portal/ArcGIS Online?  If it's a KML Service I would think that it should work exactly like a Map Service.  However, if it's a KML file, the data should just be able to be downloaded.  Not viewed.

**Comment by ecaldwell** [comment]
Yes, I'm seeing the same thing. KML files stored in Portal work as expected (download link is provided), KMLs registered from the web show the `code: 500` message. I'm gonna send this to the dev team and see if they are handling it differently on the back end.

**Comment by ecaldwell** [comment]
Finally got an official answer on this. It's the result of how that particular item is being stored on the backend. Using the [Item Types documentation](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Items_and_item_types/02r3000000ms000000/) as a reference, you'll see that KML specifically can be either File or KMZ (depending on how the item was added).
![screen shot 2015-09-23 at 12 13 02 pm](https://cloud.githubusercontent.com/assets/240542/10050950/e7b601a8-61ec-11e5-99fe-95c799971736.png)

Many of the other service types have Text/JSON which is basically because **more is known about those types and Portal stores a little bit of additional information on the backend.**

I'd like to see the API be a little more agnostic to registered services and return similar responses regardless of the type. It was noted, but I don't expect to see any change made based on my particular opinion. 

So I guess the final question here is: do you think ArcGIS Online Assistant should handle data responses with an error message any differently (rather than passing them straight through to the data panel as it does now)?
